# -*- coding: utf-8 -*-
"""Projeto-Infinity-Estatistica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NJpNz1l2AbChWCuJF5fgOLuhD7lG7Q6G

# Import das Bibliotecas
"""

import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path = ('/content/drive/MyDrive/iris.csv')

df = pd.read_csv(path)

df

"""# Questões"""

# PROJETO 1 - ESTATISTICA - INFINITY SCHOOL

#PRIMEIRA QUESTÃO:
#Determine a ÿrequência de cada classe (Setosa, Virginica e Versicolor):

print(df['variety'].value_counts().to_frame())

#SEGUNDA QUESTÃO:
# #Calcule a média para a largura (sepal.width) e Comprimento (sepal.length)
# da sépala de cada classe(Setosa, Virginica e Versicolor):

#Setosa:
print(" Média da Largura da Flor Setosa:",df[df['variety']== 'Setosa']['sepal.width'].mean())
print(" Média do Comprimento da Flor Setosa:",df[df['variety']== 'Setosa']['sepal.length'].mean())
#Virginica:
print("\n Média da Largura da Flor Virginica:",df[df['variety']== 'Virginica']['sepal.width'].mean())
print(" Média do Comprimento da Flor Virginica:",df[df['variety']== 'Virginica']['sepal.length'].mean())
#Versicolor:
print("\n Média da Largura da Flor Versicolor:",df[df['variety']== 'Versicolor']['sepal.width'].mean())
print(" Média do Comprimento da Flor Versicolor:",df[df['variety']== 'Versicolor']['sepal.length'].mean())

#TERCEIRA QUESTÃO
# Qual das classes apresenta o maior desvio padrão
# em relação ao comprimento da pétala (petal.length)?

#Setosa:
print(" Desvio Padrão do Comprimento da Flor Setosa:",df[df['variety']== 'Setosa']['sepal.length'].std())
#Virginica:
print(" Desvio Padrão do Comprimento da Flor Virginica:",df[df['variety']== 'Virginica']['sepal.length'].std())
#Versicolor:
print(" Desvio Padrão do Comprimento da Flor Versicolor:",df[df['variety']== 'Versicolor']['sepal.length'].std())

#QUARTA QUESTÃO:
#Determine a correlação para cada classe em
#relação a largura e comprimento da pétala:

#Setosa:
print(df[df['variety']== 'Setosa'][['sepal.width','sepal.length']].corr())
print("\n")
#Virginica:
print(df[df['variety']== 'Virginica'][['sepal.width','sepal.length']].corr())
print("\n")
#Versicolor:
print(df[df['variety']== 'Versicolor'][['sepal.width','sepal.length']].corr())

df['variety']== 'Setosa'

#QUINTA QUESTÃO:
# Construa o boxplot das 3 classes (Setosa, Versicolor e Virginica)
# para o comprimento da sépala (sepal.length), conforme figura
# abaixo:
setosa = df[df['variety']== 'Setosa']['sepal.length']
Versicolor = df[df['variety']== 'Versicolor']['sepal.length']
Virginica = df[df['variety']== 'Virginica']['sepal.length']

plt.title('Boxplot- íris')
plt.xlabel('Tipos de Flores')
plt.boxplot([setosa,Versicolor,Virginica])
plt.show()

