# -*- coding: utf-8 -*-
"""Revisao-Projeto.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azRSaAs1Xf6auKmht75XbVyfQgvyH8ap

# Import Variaveis
"""

import pandas as pd

import matplotlib.pyplot as plt

"""# Codigo"""

data

data = pd.DataFrame({
"Nota" :  [10, 9, 6, 8, 4, 2, 0],
"Horas de Estudo" : [20, 18, 10, 13, 6, 2, 1],
"Horas de Sono" : [8, 8, 5, 7, 2, 1, 1]
})

#Media
data.mean()

#Frequencia
data['Horas de Sono'].value_counts().to_frame()

#Desvio Padrão
data['Nota'].std()

#Variancia
data['Nota'].var()

#Correlação
data[['Nota','Horas de Estudo']].corr()

#Covariancia
data.cov()

plt.boxplot(data['Nota'])
plt.title('Boxplot das Notas')
plt.show()

#q varia [0,1] // 1q = 0.25, 2q= 0.5, 3q = 0.75, max = 1, min = 0
data['Nota'].quantile(q=1)